#!/usr/bin/env python3
"""hermes aqua-cortex — terminal surface for the aqua_cortex RAG index.

Subcommands
-----------
  hermes aqua-cortex query "free-text question"
      Hybrid search (lexical + vector) on the Meilisearch index, send the
      top chunks to the existing llama.cpp /v1/chat/completions endpoint,
      and print a citation-bearing answer.

  hermes aqua-cortex snapshot
      Emit a static JSON snapshot of the joined index — the same payload the
      Grafana "aqua_cortex" panel pulls. Useful for local sanity checks
      and as a cron target that the panel import flow can rely on without
      a long-running cortex API server.

  hermes aqua-cortex ping
      Sanity check: print whether the configured Meilisearch index exists
      and has any documents, plus whether the llama.cpp /v1/embeddings
      endpoint responds. Exits non-zero on any failure.

Design choices
--------------
* No long-running cortex API service is required for v1. The CLI talks
  directly to Meilisearch + llama.cpp over HTTPS — both already on the
  home swarm, both reachable from the operator's terminal and from inside
  Swarm containers.

* Citations are parsed out of the chunk metadata, not generated by the
  LLM. The system prompt instructs the model to answer using ONLY the
  provided chunks; we then prepend the citations deterministically. This
  keeps hallucinated sources out of the output even when the model drifts.

* Configuration is read from the repo's `aqua_cortex.toml` (same source
  of truth as the indexer) so a single edit covers indexer + CLI + panel.
  CLI-specific overrides come from env vars (HERMES_AQUA_CORTEX_*).

Cluster isolation
-----------------
* Reads only. No writes to Meilisearch, no writes to Obsidian, no writes
  to the kanban DB, no writes to the Aqua swarm.
* The CLI runs on the operator's terminal (or anywhere with HTTPS to
  meili.loc.wallacearizona.us + llama.loc.wallacearizona.us). It does NOT
  deploy as a Swarm service in v1.
"""

from __future__ import annotations

import argparse
import dataclasses
import json
import logging
import os
import sys
import textwrap
from pathlib import Path
from typing import Any, Iterable

import httpx

# Allow `python hermes_aqua_cortex.py ...` from anywhere. The plugin loads
# the same cortex.config / cortex.schema modules the indexer uses, which
# keeps the Meilisearch URL, master-key path, and embedder dim in lockstep.
_REPO_ROOT = Path(__file__).resolve().parent.parent
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

from cortex.config import IndexerConfig  # noqa: E402  (sys.path mutation above)
from cortex.schema import CortexDocument, LiveState  # noqa: E402


log = logging.getLogger("hermes_aqua_cortex")


# ---------------------------------------------------------------------------
# Config + env overrides
# ---------------------------------------------------------------------------


@dataclasses.dataclass
class CLIConfig:
    """Subcommand runtime knobs. Sourced from IndexerConfig + env overrides."""

    meili_url: str
    meili_index: str
    meili_api_key: str
    llama_url: str
    llama_model: str
    llama_api_key: str | None
    top_k: int
    http_timeout_s: float
    verify_tls: bool

    @classmethod
    def load(cls) -> "CLIConfig":
        cfg = IndexerConfig.load()
        # Prefer env overrides so a one-shot `HERMES_AQUA_CORTEX_MEILI_URL=...`
        # can repoint the CLI without editing aqua_cortex.toml.
        meili_url = os.environ.get("HERMES_AQUA_CORTEX_MEILI_URL") or cfg.meili_url
        meili_index = os.environ.get("HERMES_AQUA_CORTEX_MEILI_INDEX") or cfg.meili_index
        llama_url = os.environ.get("HERMES_AQUA_CORTEX_LLAMA_URL") or cfg.llama_url
        llama_model = os.environ.get("HERMES_AQUA_CORTEX_LLAMA_MODEL") or cfg.llama_model

        key_path = os.environ.get("HERMES_AQUA_CORTEX_MEILI_KEY_FILE") or cfg.meili_key_file
        try:
            with open(key_path, "r", encoding="utf-8") as fh:
                meili_api_key = fh.read().strip()
        except OSError as exc:
            raise SystemExit(
                f"hermes-aqua-cortex: cannot read Meilisearch key from {key_path}: {exc}"
            )

        return cls(
            meili_url=meili_url.rstrip("/"),
            meili_index=meili_index,
            meili_api_key=meili_api_key,
            llama_url=llama_url.rstrip("/"),
            llama_model=llama_model,
            llama_api_key=os.environ.get("HERMES_AQUA_CORTEX_LLAMA_API_KEY"),
            top_k=int(os.environ.get("HERMES_AQUA_CORTEX_TOP_K", "5")),
            http_timeout_s=float(os.environ.get("HERMES_AQUA_CORTEX_TIMEOUT_S", "30")),
            verify_tls=os.environ.get("HERMES_AQUA_CORTEX_VERIFY_TLS", "1") not in ("0", "false", "False"),
        )


# ---------------------------------------------------------------------------
# Meilisearch hybrid search
# ---------------------------------------------------------------------------


def _headers(cfg: CLIConfig) -> dict[str, str]:
    h = {"Authorization": f"Bearer {cfg.meili_api_key}"}
    return h


def search_chunks(cfg: CLIConfig, query: str, *, limit: int = 5) -> list[dict[str, Any]]:
    """Hybrid search: lexical `q` + dense `vector` against the same `query`.

    Falls back to lexical-only if embedding fails (e.g. llama.cpp down).
    Returns the raw `hits` array as Meilisearch delivered it (already in
    field-flattened form because the indexer serializes `live_state` inline).
    """
    body: dict[str, Any] = {
        "q": query,
        "limit": limit,
        "attributesToRetrieve": [
            "id",
            "source",
            "application",
            "doc_path",
            "doc_title",
            "section",
            "section_anchor",
            "chunk_index",
            "chunk_text",
            "linked_services",
            "linked_cards",
            "linked_commits",
            "live_state",
            "indexed_at",
        ],
        "showRankingScore": True,
    }
    # Try to add a dense vector. If the embed endpoint is unreachable, we
    # fall back to lexical-only — still useful, just less precise.
    #
    # Meilisearch 1.12 hybrid search contract: when `vector` is supplied,
    # `hybrid` MUST also be present (and vice versa). The embedder name
    # must match what was configured at index time (default: "default").
    try:
        vec = embed_query(cfg, query)
        body["vector"] = vec
        body["hybrid"] = {"embedder": "default", "semanticRatio": 0.5}
    except Exception as exc:  # noqa: BLE001 — surface the failure in `--verbose`
        log.warning("vector embedding failed (%s); falling back to lexical-only", exc)

    url = f"{cfg.meili_url}/indexes/{cfg.meili_index}/search"
    with httpx.Client(timeout=cfg.http_timeout_s, verify=cfg.verify_tls) as client:
        r = client.post(url, json=body, headers=_headers(cfg))
        r.raise_for_status()
        data = r.json()
    return data.get("hits", [])


def embed_query(cfg: CLIConfig, query: str) -> list[float]:
    """Embed a single query via the OpenAI-compatible /v1/embeddings endpoint."""
    body = {"input": query, "model": cfg.llama_model}
    url = f"{cfg.llama_url}/v1/embeddings"
    headers: dict[str, str] = {"Content-Type": "application/json"}
    if cfg.llama_api_key:
        headers["Authorization"] = f"Bearer {cfg.llama_api_key}"
    with httpx.Client(timeout=cfg.http_timeout_s, verify=cfg.verify_tls) as client:
        r = client.post(url, json=body, headers=headers)
        r.raise_for_status()
        data = r.json()
    vec = data["data"][0]["embedding"]
    if not isinstance(vec, list) or not vec:
        raise RuntimeError("embedding endpoint returned empty vector")
    return vec


# ---------------------------------------------------------------------------
# Citation formatting
# ---------------------------------------------------------------------------


def _citation_lines(hits: Iterable[dict[str, Any]], *, max_per_kind: int = 8) -> list[str]:
    """Build the deterministic Sources: list from chunk metadata.

    Format (one line per source):
      - <doc_path>#<section_anchor>           (obsidian doc + section)
      - kanban:t_<hex>                         (linked kanban card)
      - swarm:<service>=<swarm_state>          (live_state)
    We dedupe (same doc+section appearing twice from different chunks
    collapses to one entry) and stable-sort so the output is reproducible.
    Each kind is capped at `max_per_kind` so a corpus-wide topic (e.g.
    "supabase" hits a chunk with 30+ linked kanban cards) doesn't bury
    the actually useful citations.
    """
    seen_doc_section: set[tuple[str, str]] = set()
    seen_cards: set[str] = set()
    seen_swarm: set[tuple[str, str]] = set()
    doc_lines: list[str] = []
    card_lines: list[str] = []
    swarm_lines: list[str] = []

    for hit in hits:
        doc_path = (hit.get("doc_path") or "").strip()
        section_anchor = (hit.get("section_anchor") or "").strip() or "#"
        if doc_path and len(doc_lines) < max_per_kind:
            key = (doc_path, section_anchor)
            if key not in seen_doc_section:
                seen_doc_section.add(key)
                doc_lines.append(f"  - {doc_path}{section_anchor}")

        for cid in hit.get("linked_cards") or []:
            if len(card_lines) >= max_per_kind:
                break
            cid = str(cid).strip()
            if cid and cid not in seen_cards:
                seen_cards.add(cid)
                card_lines.append(f"  - kanban:{cid}")

        ls = hit.get("live_state")
        if isinstance(ls, dict):
            service = (ls.get("service") or "").strip()
            state = (ls.get("swarm_state") or "").strip()
            if service and state and len(swarm_lines) < max_per_kind:
                k = (service, state)
                if k not in seen_swarm:
                    seen_swarm.add(k)
                    swarm_lines.append(f"  - swarm:{service}={state}")

    # Stable sort within each kind; group kinds together.
    lines = sorted(doc_lines) + sorted(card_lines) + sorted(swarm_lines)
    return lines


# ---------------------------------------------------------------------------
# LLM answer generation
# ---------------------------------------------------------------------------


_SYSTEM_PROMPT = textwrap.dedent(
    """\
    You are aqua_cortex, a retrieval-grounded assistant for the AquaButler
    pool deployment. You answer using ONLY the numbered chunks below.
    Each chunk is prefixed with `[<n>] path#anchor`. When you use a fact
    from a chunk, append `(<n>)` after the sentence that uses it. If the
    chunks do not contain the answer, reply exactly: "No matching context."
    Do not invent services, commit SHAs, kanban card ids, or swarm states.
    """
).strip()


def _looks_broken(text: str) -> bool:
    """Heuristic for Qwen2.5-1.5B-Instruct going off the rails.

    The home llama.cpp deployment occasionally produces degenerate output
    (single-token loops, garbage tokens, half-translated sentences). The
    quality detection we ship here is conservative — if any of these trip
    we treat the LLM output as untrustworthy and fall back to an
    extractive answer built directly from the top chunks.

    Triggers (any one is enough):
      - Output is shorter than 20 chars (LLM said "I don't know" or similar)
      - Output repeats the same 1-3 token bigram more than 8 times
      - More than 40% of words are the same single word
    """
    if len(text) < 20:
        return True
    words = text.split()
    if not words:
        return True
    # Single-word-dominance: 1 word = >40% of total.
    counts: dict[str, int] = {}
    for w in words:
        counts[w] = counts.get(w, 0) + 1
    top_word, top_count = max(counts.items(), key=lambda kv: kv[1])
    if top_count / max(len(words), 1) > 0.4:
        return True
    # Bigram repetition: same 2-word window > 8 times.
    bigrams: dict[tuple[str, str], int] = {}
    for i in range(len(words) - 1):
        bg = (words[i], words[i + 1])
        bigrams[bg] = bigrams.get(bg, 0) + 1
    if bigrams and max(bigrams.values()) > 8:
        return True
    return False


def _extractive_answer(query: str, hits: list[dict[str, Any]]) -> str:
    """Deterministic fallback when the LLM produces degenerate output.

    We pick the top 2 chunks, return a short headline + their first
    paragraph as the "answer". The user still gets useful text plus
    the Sources list (which is the real value of this CLI anyway).
    """
    if not hits:
        return "No matching context."
    snippets: list[str] = []
    for h in hits[:2]:
        text = (h.get("chunk_text") or "").strip().splitlines()
        # First non-empty paragraph.
        para = next((ln for ln in text if ln.strip()), "")
        if len(para) > 240:
            para = para[:237].rstrip() + "..."
        title = h.get("doc_title") or h.get("doc_path") or "?"
        snippets.append(f"[{title}] {para}")
    return "Top matching context (LLM output was untrustworthy; using extractive fallback):\n\n" + "\n\n".join(snippets)


def answer_question(
    cfg: CLIConfig,
    query: str,
    hits: list[dict[str, Any]],
    *,
    max_tokens: int = 512,
    temperature: float = 0.1,
) -> str:
    """Call llama.cpp /v1/chat/completions with the chunks as context.

    Falls back to an extractive answer when the model produces degenerate
    output (the home Qwen2.5-1.5B-Instruct quant occasionally goes off
    the rails; see `_looks_broken`).
    """
    if not hits:
        return "No matching context."

    numbered = []
    for i, hit in enumerate(hits, start=1):
        path = hit.get("doc_path", "?")
        anchor = hit.get("section_anchor") or "#"
        text = (hit.get("chunk_text") or "").strip()
        numbered.append(f"[{i}] {path}{anchor}\n{text}")
    context_block = "\n\n---\n\n".join(numbered)

    user_msg = (
        f"Question: {query}\n\n"
        f"Context chunks:\n\n{context_block}\n\n"
        "Answer using only the chunks above. Cite chunk numbers in parens."
    )

    body = {
        "model": cfg.llama_model,
        "messages": [
            {"role": "system", "content": _SYSTEM_PROMPT},
            {"role": "user", "content": user_msg},
        ],
        "temperature": temperature,
        "max_tokens": max_tokens,
        "stream": False,
    }
    url = f"{cfg.llama_url}/v1/chat/completions"
    headers: dict[str, str] = {"Content-Type": "application/json"}
    if cfg.llama_api_key:
        headers["Authorization"] = f"Bearer {cfg.llama_api_key}"
    try:
        with httpx.Client(timeout=cfg.http_timeout_s, verify=cfg.verify_tls) as client:
            r = client.post(url, json=body, headers=headers)
            r.raise_for_status()
            data = r.json()
        try:
            answer = data["choices"][0]["message"]["content"].strip()
        except (KeyError, IndexError, TypeError) as exc:
            raise RuntimeError(f"unexpected chat completion payload: {data!r}") from exc
    except Exception as exc:  # noqa: BLE001
        log.warning("LLM call failed (%s); using extractive fallback", exc)
        return _extractive_answer(query, hits)

    if _looks_broken(answer):
        log.warning("LLM output looked degenerate; using extractive fallback")
        return _extractive_answer(query, hits)
    return answer


# ---------------------------------------------------------------------------
# Snapshot (for Grafana datasource)
# ---------------------------------------------------------------------------


def _doc_to_snapshot(doc: dict[str, Any]) -> dict[str, Any]:
    """Flatten one Meilisearch hit into the Grafana-friendly snapshot shape.

    The Grafana JSON datasource renders rows from this; the field names
    become column keys. Keep this stable — Grafana panels bind to it.
    """
    ls = doc.get("live_state") or {}
    return {
        "service": (ls.get("service") if isinstance(ls, dict) else None) or "",
        "documented": bool(doc.get("doc_path")),
        "running": isinstance(ls, dict) and bool(ls.get("service")),
        "swarm_state": (ls.get("swarm_state") if isinstance(ls, dict) else None) or "",
        "stack": (ls.get("stack") if isinstance(ls, dict) else None) or "",
        "node": (ls.get("node") if isinstance(ls, dict) else None) or "",
        "doc_path": doc.get("doc_path", ""),
        "doc_title": doc.get("doc_title", ""),
        "section": doc.get("section") or "",
        "section_anchor": doc.get("section_anchor") or "",
        "oldest_doc_indexed_at": doc.get("indexed_at", ""),
        "last_compose_change": "",  # populated by snapshot linker (git_state join)
        "source": doc.get("source", ""),
        "linked_cards": doc.get("linked_cards") or [],
        "linked_commits": doc.get("linked_commits") or [],
        "linked_services": doc.get("linked_services") or [],
        "checked_at": (ls.get("checked_at") if isinstance(ls, dict) else "") or "",
    }


def _list_all_documents(cfg: CLIConfig, *, page_size: int = 1000) -> list[dict[str, Any]]:
    """Walk the full index via paginated /documents listing.

    Meilisearch 1.x supports GET /indexes/{uid}/documents?limit=&offset=.
    For the cortex corpus (~500 docs) one or two pages is plenty.
    """
    url = f"{cfg.meili_url}/indexes/{cfg.meili_index}/documents"
    headers = _headers(cfg)
    out: list[dict[str, Any]] = []
    offset = 0
    while True:
        with httpx.Client(timeout=cfg.http_timeout_s, verify=cfg.verify_tls) as client:
            r = client.get(url, params={"limit": page_size, "offset": offset}, headers=headers)
            r.raise_for_status()
            data = r.json()
        results = data.get("results", [])
        if not results:
            break
        out.extend(results)
        if len(results) < page_size:
            break
        offset += page_size
        if offset > 20000:  # hard cap; cortex corpus is much smaller
            break
    return out


def build_snapshot(cfg: CLIConfig) -> dict[str, Any]:
    """Build the Grafana-datasource-shaped snapshot of the joined index."""
    raw = _list_all_documents(cfg)
    docs = [_doc_to_snapshot(d) for d in raw]

    # "Recent activity" — last 50 indexed, regardless of doc_path duplication.
    recent = sorted(
        ({"when": d.get("oldest_doc_indexed_at", ""),
          "source": d.get("source", ""),
          "summary": (d.get("doc_title") or d.get("doc_path") or ""),
          "service": d.get("service", ""),
          "doc_path": d.get("doc_path", "")} for d in docs),
        key=lambda r: r.get("when") or "",
        reverse=True,
    )[:50]

    # Doc freshness view — distinct (doc_path, doc_title).
    seen_paths: set[str] = set()
    freshness: list[dict[str, Any]] = []
    for d in docs:
        path = d.get("doc_path")
        if not path or path in seen_paths:
            continue
        seen_paths.add(path)
        freshness.append({
            "service": d.get("service", "") or path,
            "doc_path": path,
            "doc_title": d.get("doc_title", ""),
            "oldest_doc_indexed_at": d.get("oldest_doc_indexed_at", ""),
            "last_compose_change": d.get("last_compose_change", ""),
        })

    # Doc-vs-running view — distinct services.
    seen_svcs: dict[str, dict[str, Any]] = {}
    for d in docs:
        svc = d.get("service") or d.get("doc_path") or ""
        if not svc or svc in seen_svcs:
            continue
        seen_svcs[svc] = d
    doc_vs_running = sorted(
        (
            {
                "service": svc,
                "documented": bool(d.get("doc_path")),
                "running": bool(d.get("running")),
                "swarm_state": d.get("swarm_state", ""),
                "stack": d.get("stack", ""),
            }
            for svc, d in seen_svcs.items()
        ),
        key=lambda r: (r["running"], r["documented"], r["service"]),
    )

    return {
        "generated_at": _now_iso(),
        "index": cfg.meili_index,
        "counts": {
            "documents": len(docs),
            "distinct_services": len(seen_svcs),
            "distinct_doc_paths": len(seen_paths),
        },
        "doc_vs_running": doc_vs_running,
        "doc_freshness": freshness,
        "recent_activity": recent,
    }


def _now_iso() -> str:
    from datetime import datetime, timezone
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


# ---------------------------------------------------------------------------
# Subcommand handlers
# ---------------------------------------------------------------------------


def cmd_query(args: argparse.Namespace) -> int:
    cfg = CLIConfig.load()
    query = args.question
    # Resolve limit: CLI --top-k > env var > config default. argparse default
    # is None so we have to apply the env/default fallback here. Meilisearch
    # rejects `limit: null` with a 400 ("expected positive integer"), so we
    # must coerce before the request.
    if args.top_k is not None:
        limit = args.top_k
    else:
        limit = cfg.top_k
    hits = search_chunks(cfg, query, limit=limit)
    if not hits:
        print("No matching context.", file=sys.stderr)
        # Still emit a Sources block (empty) so downstream tools can
        # parse uniformly. Exit non-zero to flag "no answer".
        print("Sources:\n  - (none)")
        return 2

    answer = answer_question(cfg, query, hits, max_tokens=args.max_tokens)
    print(answer)

    sources = _citation_lines(hits)
    print("\nSources:")
    if sources:
        for line in sources:
            print(line)
    else:
        print("  - (chunks present but no extractable citations)")

    return 0


def cmd_snapshot(args: argparse.Namespace) -> int:
    cfg = CLIConfig.load()
    snap = build_snapshot(cfg)
    # Silence the noisy httpx INFO logs that would otherwise pollute the
    # JSON output (snapshots are piped to files / Grafana datasources).
    logging.getLogger("httpx").setLevel(logging.WARNING)
    json.dump(snap, sys.stdout, indent=2, sort_keys=True)
    sys.stdout.write("\n")
    return 0


def cmd_ping(args: argparse.Namespace) -> int:
    cfg = CLIConfig.load()
    failures: list[str] = []

    # Meilisearch index check.
    try:
        with httpx.Client(timeout=cfg.http_timeout_s, verify=cfg.verify_tls) as client:
            r = client.get(
                f"{cfg.meili_url}/indexes/{cfg.meili_index}/stats",
                headers=_headers(cfg),
            )
            r.raise_for_status()
            stats = r.json()
        print(f"meili  : OK ({stats.get('numberOfDocuments', '?')} docs in '{cfg.meili_index}')")
    except Exception as exc:  # noqa: BLE001
        failures.append(f"meili: {exc}")
        print(f"meili  : FAIL ({exc})")

    # llama.cpp embeddings check.
    try:
        vec = embed_query(cfg, "ping")
        print(f"llama  : OK (dim={len(vec)})")
    except Exception as exc:  # noqa: BLE001
        failures.append(f"llama: {exc}")
        print(f"llama  : FAIL ({exc})")

    return 0 if not failures else 1


# ---------------------------------------------------------------------------
# argparse
# ---------------------------------------------------------------------------


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        prog="hermes aqua-cortex",
        description="Terminal surface for the aqua_cortex RAG index.",
    )
    sub = p.add_subparsers(dest="cmd", required=True)

    p_query = sub.add_parser("query", help="Ask a question; print answer + sources")
    p_query.add_argument("question", help="Free-text question")
    p_query.add_argument("--top-k", type=int, default=None,
                         help="Override HERMES_AQUA_CORTEX_TOP_K (default 5)")
    p_query.add_argument("--max-tokens", type=int, default=512,
                         help="Max tokens for the answer (default 512)")
    p_query.set_defaults(func=cmd_query)
    p_snap = sub.add_parser("snapshot", help="Emit Grafana-datasource JSON snapshot")
    p_snap.set_defaults(func=cmd_snapshot)

    p_ping = sub.add_parser("ping", help="Sanity check Meilisearch + llama.cpp")
    p_ping.set_defaults(func=cmd_ping)

    return p


def main(argv: list[str] | None = None) -> int:
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s %(levelname)s %(name)s %(message)s",
    )
    parser = build_parser()
    args = parser.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
